version: '2'
services:
  gubbns:
    build: .
    command: gubbns -J-Xmx256M -J-Xms256M -Dpidfile.path=/dev/null
    environment:
      - COUCHDB_HOST=couchdb
    expose:
      - "9000"
    ports:
      - "9000:9000"
    links:
      - couchdb:couchdb
    restart: always
  couchdb:
    build:
      dockerfile: Dockerfile-couchdb
      context: .
    restart: always
  dockup:
    image: slakah/dockup-gs
    volumes_from:
      - couchdb
    command: >
      gs://gubbns-backup/gubbns/
      /usr/local/var/lib/couchdb
      --cron-time '32 4 * * *'
      --backup-name gubbns
      --gc-key '${GCLOUD_GUBBNS_BACKUP_KEY}'
    restart: always
