package components

import services._
import repositories.{CouchPostRepositoryComponent, PlayCouchServiceComponent}


trait Default extends Repositories with PostsComponent with PegdownServiceComponent

trait Repositories extends PlayCouchServiceComponent with CouchPostRepositoryComponent