package components

import services._
import repositories.{PlayCouchServiceComponent, PlayBlogCouchServiceComponent, CouchPostRepositoryComponent}


trait Default extends Repositories with PostsComponent with PegdownServiceComponent

trait Repositories extends PlayCouchServiceComponent with PlayBlogCouchServiceComponent with CouchPostRepositoryComponent